set_property -dict { PACKAGE_PIN E3    IOSTANDARD LVCMOS33 } [get_ports { clk }];

set_property IOSTANDARD LVCMOS33 [get_ports reset] 
set_property IOSTANDARD LVCMOS33 [get_ports din] 
set_property IOSTANDARD LVCMOS33 [get_ports sel]  
set_property IOSTANDARD LVCMOS33 [get_ports max_out] 
set_property IOSTANDARD LVCMOS33 [get_ports min_out] 
set_property IOSTANDARD LVCMOS33 [get_ports reg_out]   

set_property PACKAGE_PIN J15 [ get_ports { reset }  ]  
set_property PACKAGE_PIN L16 [ get_ports { din[0] }  ] 
set_property PACKAGE_PIN M13 [ get_ports { din[1] }  ] 
set_property PACKAGE_PIN R15 [ get_ports { din[2] }  ] 
set_property PACKAGE_PIN V10 [ get_ports { din[3] }  ]  
set_property PACKAGE_PIN R17 [ get_ports { sel[0] }  ] 
set_property PACKAGE_PIN T18 [ get_ports { sel[1] }  ] 
set_property PACKAGE_PIN H17 [ get_ports { max_out[0] }  ] 
set_property DIFF_TERM false [ get_ports { max_out[0] }  ]
set_property PACKAGE_PIN K15 [ get_ports { max_out[1] }  ] 
set_property PACKAGE_PIN J13 [ get_ports { max_out[2] }  ] 
set_property PACKAGE_PIN N14 [ get_ports { max_out[3] }  ]   
set_property PACKAGE_PIN R18 [ get_ports { min_out[0] }  ] 
set_property PACKAGE_PIN V17 [ get_ports { min_out[1] }  ] 
set_property PACKAGE_PIN U17 [ get_ports { min_out[2] }  ] 
set_property PACKAGE_PIN U16 [ get_ports { min_out[3] }  ]  
set_property PACKAGE_PIN V16 [ get_ports { reg_out[0] }  ] 
set_property PACKAGE_PIN T15 [ get_ports { reg_out[1] }  ] 
set_property PACKAGE_PIN U14 [ get_ports { reg_out[2] }  ] 
set_property PACKAGE_PIN T16 [ get_ports { reg_out[3] }  ]