// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4K94DEPyFfVZVUSR40Vu7w34ApSabHRI',
    appId: '1:596234566738:web:92846eb9ad07bf3ba4f38b',
    messagingSenderId: '596234566738',
    projectId: 'growpulse-d7198',
    authDomain: 'growpulse-d7198.firebaseapp.com',
    databaseURL: 'https://growpulse-d7198-default-rtdb.firebaseio.com',
    storageBucket: 'growpulse-d7198.appspot.com',
    measurementId: 'G-RKPM1BTP2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMW72xYF6UUP71OBE8Bd6LvkxRpZ9E_xM',
    appId: '1:596234566738:android:177b507b75296468a4f38b',
    messagingSenderId: '596234566738',
    projectId: 'growpulse-d7198',
    databaseURL: 'https://growpulse-d7198-default-rtdb.firebaseio.com',
    storageBucket: 'growpulse-d7198.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIFLXN9j29bSyacQ6f7Qd0XMVlA2uQngI',
    appId: '1:596234566738:ios:aa7d24f28e8cb26ca4f38b',
    messagingSenderId: '596234566738',
    projectId: 'growpulse-d7198',
    databaseURL: 'https://growpulse-d7198-default-rtdb.firebaseio.com',
    storageBucket: 'growpulse-d7198.appspot.com',
    iosBundleId: 'com.example.flutterCapstoneGrowpulse',
  );
}
